### ISSUE TITLE
Server-side rendering isn't working

### ISSUE THREAD

**Issue by Giuseppetm** [Octanium91/react-app-ssr#2]
With `npm run ssr:start` nothing appears on localhost:3006
It just runs the usual `npm start` and shows the app on localhost:3000

Any suggestions?

![image](https://user-images.githubusercontent.com/52317197/184139795-0ebf94f8-f1de-4385-b5e5-0708486f9064.png)

**Comment by Octanium91** [comment]
try first do command 'npm run build' and then 'npm run ssr:start'
